# Import main calculation function

### Importing the library

In [1]:
from geopolrisk.assessment.main import (
    gprs_calc,
)  # This is a one stop function to calculate all the values of the GeoPolRisk method

Reading table/s ['Aluminium', 'Antimony', 'Arsenic', 'Asbestos', 'Baryte', 'Bauxite', 'Bentonite', 'Beryllium (conc.)', 'Bismuth', 'Boron Minerals', 'Cadmium', 'Chromium (Cr2O3)', 'Cobalt', 'Coking Coal', 'Copper', 'Diamonds (Gem)', 'Diamonds (Ind)', 'Diatomite', 'Feldspar', 'Fluorspar', 'Gallium', 'Germanium', 'Gold', 'Graphite', 'Gypsum and Anhydrite', 'Indium', 'Iron (Fe)', 'Kaolin (China-Clay)', 'Lead', 'Lignite', 'Lithium (Li2O)', 'logging', 'Magnesite', 'Manganese', 'Mercury', 'Molybdenum', 'Natural Gas', 'Nickel', 'Niobium (Nb2O5)', 'Oil Sands (part of Petroleum)', 'Oil Shales', 'Palladium', 'Perlite', 'Petroleum', 'Phosphate Rock (P2O5)', 'Platinum', 'Potash (K2O)', 'Rare Earths (REO)', 'Rhenium', 'Rhodium', 'Salt (rock, brines, marine)', 'Selenium', 'Silver', 'Steam Coal', 'Sulfur (elementar & industrial)', 'Talc, Steatite & Pyrophyllite', 'Tantalum (Ta2O5)', 'Tellurium', 'Tin', 'Titanium (TiO2)', 'Tungsten (W)', 'Uranium (U3O8)', 'Vanadium (V)', 'Vermiculite', 'Zinc', 'Zircon', 'Country_ISO', 'HS Code Map'] from the library database /opt/anaconda3/envs/build_gprs/lib/python3.11/site-packages/geopolrisk/lib/world_mining_data.db.: 100%|██████████| 68/68 [00:00<00:00, 3307.04it/s]
Reading table/s ['Normalized'] from the library database /opt/anaconda3/envs/build_gprs/lib/python3.11/site-packages/geopolrisk/lib/wgi.db.: 100%|██████████| 1/1 [00:00<00:00, 544.64it/s]
Reading table/s ['baci_trade'] from the library database /opt/anaconda3/envs/build_gprs/lib/python3.11/site-packages/geopolrisk/lib/baci.db.: 100%|██████████| 1/1 [00:14<00:00, 14.51s/it]

## Prepare the lists

In [2]:
from geopolrisk.assessment.utils import (
    default_rmlist,
)  # This is a functions that returns the default list of metals that are available in the library database

ListofMetals = default_rmlist()
ListofAlternateMetals = [
    "Aluminium",
    "Copper",
    "Nickel",
    "Tin",
    "Zinc",
]  # If you want to use a different list of metals, you can specify them here (of course, they must be available in the library database)
# Aluminium is an exception in the database, it refers to primary metal not raw material. The raw material is bauxite

ListofCountries = [
    "China",
    "Germany",
    842,
    36,
]  # List of countries to be assessed, you can use the ISO 3166-1 numeric code & "EU" for European Union

ListofYear = [
    2024
]  # List of years to be assessed, you can only use the year as an integer

In [3]:
gprs_calc(
    ListofYear, ListofCountries, ListofMetals
)  # This is the main function that calculates the GeoPolRisk values for the specified list of countries, years and metals
# The function returns a pandas DataFrame with the results, which is also saved as an excel file in a folder named "ouput" in the document folder of the users home directory

Calculating the GeoPolRisk: 100%|██████████| 212/212 [00:01<00:00, 119.14it/s]

,DBID,Country [Economic Entity],Raw Material,Year,GeoPolRisk Score,GeoPolRisk Characterization Factor [eq. Kg-Cu/Kg],HHI,Import Risk,Price
0,Aluminium1562024,China,Aluminium,2024,0.010682,0.064901,0.371913,0.028722,2.487424
1,Antimony1562024,China,Antimony,2024,0.069778,0.657092,0.212862,0.327806,3.855414
2,Arsenic1562024,China,Arsenic,2024,0.000014,0.016849,0.413746,0.000034,493.710942
3,Asbestos1562024,China,Asbestos,2024,0.107030,0.071268,0.342183,0.312788,0.272613
4,Baryte1562024,China,Baryte,2024,0.002107,0.000305,0.135958,0.015494,0.059344
...,...,...,...,...,...,...,...,...,...
207,Tungsten362024,Australia,Tungsten,2024,0.005054,0.688157,0.614628,0.008224,55.740563
208,Uranium362024,Australia,Uranium,2024,0.000000,0.000000,0.231853,0.000000,0.000000
209,Vanadium362024,Australia,Vanadium,2024,0.309338,14.325611,0.512731,0.603315,18.960119
210,Zinc362024,Australia,Zinc,2024,0.013352,0.035114,0.142906,0.093435,1.076673
211,Zirconium362024,Australia,Zirconium,2024,0.000303,0.001096,0.159073,0.001906,1.479378

# Testing individual functions for the same list

In [ ]:
import random

RandomMetal = random.choice(ListofMetals)
RandomCountry = random.choice(ListofCountries)
RandomYear = random.choice(ListofYear)

In [ ]:
from geopolrisk.assessment.core import (
    HHI,
)  # This is the Herfindahl-Hirschman Index function to calculate the concentration of production in a country for a specific metal and year


ProductionQuantity, hhi = HHI(RandomMetal, RandomYear, RandomCountry)

In [ ]:
from geopolrisk.assessment.core import (
    importrisk,
)  # This is the function to import risk values for a specific metal, year and country from the mapped baci data


from geopolrisk.assessment.utils import (
    mapped_baci,
)  # This is a function to get the mapped baci data, which is a pandas DataFrame with the trade data for the specified countries, years and metals

mapped_baci = (
    mapped_baci()
)  # This is a function that returns the mapped baci data, which is a pandas DataFrame with the trade data for the specified countries, years and metals


Numerator, TotalTrade, Price = importrisk(
    RandomMetal, RandomYear, RandomCountry, data=mapped_baci
)  # The functions returns the values required to calculate the import risk for the specified metal, year and country
# The values are the numerator of the import risk formula (i.e. the import share wieghted by the political stability of the exporting countries), the total trade value and the price of the metal in USD per kilogram

In [ ]:
from geopolrisk.assessment.core import (
    GeoPolRisk,
)  # This is the main function to calculate the GeoPolRisk values based on the numerator, total trade, price, production quantity and Herfindahl-Hirschman Index


Values = GeoPolRisk(
    Numerator, TotalTrade, Price, ProductionQuantity, hhi
)  # This function returns a dictionary with the GeoPolRisk values for the specified metal, year and country
# The values are the GeoPolRisk Score, the characterization factor, the import risk

In [ ]:
Values
"""
The three values correspond to "the GeoPolRisk Score", "the characterization factor (GSP)", "the import risk component"
"""

'\nThe three values correspond to "the GeoPolRisk Score", "the characterization factor (GSP)", "the import risk component"\n'

# Testing company level functions using same data as above

In [ ]:
from geopolrisk.assessment.core import importrisk_company

"""
Modify the template file located in the the 'geopolrisk/database' location of the document directory.
This function calculates the import risk values for a specific metal, year and country based on the company data in the database folder.
"""



Numerator_C, TotalTrade_C, Price_C = importrisk_company("Nickel", 2022)

Values_c = GeoPolRisk(Numerator_C, TotalTrade_C, Price_C, ProductionQuantity, hhi)

  rawMaterial  partnerDesc    qty  cifvalue  period  Notes  partnerISO  \
0      Nickel      Denmark  170.0    3196.0    2022    NaN         208
1      Nickel  Netherlands    1.0      73.0    2022    NaN         528
2      Nickel     Portugal  893.0    2782.0    2022    NaN         620
3      Nickel        Egypt    4.0     113.0    2022    NaN         818
4      Nickel          USA  498.0    3355.0    2022    NaN         842

   partnerWGI cmdCode reporterDesc  reporterISO
0    0.326998  Nickel      Company          999
1    0.356539  Nickel      Company          999
2    0.327856  Nickel      Company          999
3    0.705611  Nickel      Company          999
4    0.507201  Nickel      Company          999

## Testing company level function using different parameters

In [ ]:
from geopolrisk.assessment.core import HHI, importrisk_company, GeoPolRisk

ExcelFile = "C:\Random Folder\Company data.xlsx"  # Specify the path to the Company data.xlsx file
SheetName = "Template"  # Specify the sheet name in the Excel file
RawMaterial = (
    "Nickel"  # Specify the raw material for which you want to import risk values
)
Year = 2022  # Specify the year for which you want to import risk values

from geopolrisk.assessment.core import (
    HHI,
)  # This is the HHI function to calculate the concentration of production in a country for a specific metal and year

ProductionQuantity, hhi = HHI(RawMaterial, Year, "Company")
""" The parameter "Company" is used to specify that the production quantity is for a company, not a country. 
In the HHI function, this will be used to get the production quantity for the specified raw material and year. 
The production Quantity should be 0 as a default value.
If the company recycles the said raw material, user can manually provide it in "metric tonnes" as unit.
"""
Num_Company, TotalTrade_Company, Price_Company = importrisk_company(RawMaterial, 2022)
Values_Company = GeoPolRisk(
    Num_Company, TotalTrade_Company, Price_Company, ProductionQuantity, hhi
)

  rawMaterial  partnerDesc    qty  cifvalue  period  Notes  partnerISO  \
0      Nickel      Denmark  170.0    3196.0    2022    NaN         208
1      Nickel  Netherlands    1.0      73.0    2022    NaN         528
2      Nickel     Portugal  893.0    2782.0    2022    NaN         620
3      Nickel        Egypt    4.0     113.0    2022    NaN         818
4      Nickel          USA  498.0    3355.0    2022    NaN         842

   partnerWGI cmdCode reporterDesc  reporterISO
0    0.326998  Nickel      Company          999
1    0.356539  Nickel      Company          999
2    0.327856  Nickel      Company          999
3    0.705611  Nickel      Company          999
4    0.507201  Nickel      Company          999

<>:3: SyntaxWarning: invalid escape sequence '\R'
<>:3: SyntaxWarning: invalid escape sequence '\R'
C:\Users\anish\AppData\Local\Temp\ipykernel_32080\2755402762.py:3: SyntaxWarning: invalid escape sequence '\R'
  ExcelFile = "C:\Random Folder\Company data.xlsx"  # Specify the path to the Company data.xlsx file

# Testing Regional Data

In [ ]:
# you can create regions or group of countries, the following is an example of how to create regions
NewRegions = {
    "EFTA": ["Iceland", "Norway", "Switzerland"],
    "NAFTA": ["Canada", "Mexico", "USA"],
}  # Liechtenstein has a customs union with Switzerland whose trade is not reported by UN Comtrade

In [ ]:
from geopolrisk.assessment.utils import regions

# This function updates the regions in the library (temporary variable only) and must be instantiated for the above new regions to be used
regions(NewRegions)

### Quickly check the regions

In [ ]:
from geopolrisk.assessment.database import databases

databases.regionslist["EFTA"]
# A quick check to see if the regions have been updated in the library

['Iceland', 'Norway', 'Switzerland']

## Main Function to run for the regional assessment

In [ ]:
gprs_calc(ListofYear, ["EFTA", "NAFTA"], ListofMetals)

Calculating the GeoPolRisk: 100%|██████████| 106/106 [00:12<00:00,  8.79it/s]

,DBID,Country [Economic Entity],Raw Material,Year,GeoPolRisk Score,GeoPolRisk Characterization Factor [eq. Kg-Cu/Kg],HHI,Import Risk,Price
0,AluminiumEFTA2022,EFTA,Aluminium,2022,0.028892,0.250305,0.353279,0.081781,3.546990
1,AntimonyEFTA2022,EFTA,Antimony,2022,0.115442,0.011542,0.276644,0.417296,0.040934
2,ArsenicEFTA2022,EFTA,Arsenic,2022,0.164176,4.912686,0.393237,0.417499,12.250974
3,AsbestosEFTA2022,EFTA,Asbestos,2022,0.189662,0.236331,0.334918,0.566294,0.510155
4,BaryteEFTA2022,EFTA,Baryte,2022,0.070911,0.034209,0.151374,0.468447,0.197513
...,...,...,...,...,...,...,...,...,...
101,TungstenNAFTA2022,NAFTA,Tungsten,2022,0.228728,18.544553,0.600702,0.380767,33.193985
102,UraniumNAFTA2022,NAFTA,Uranium,2022,0.021769,5.251664,0.247032,0.088121,98.770603
103,VanadiumNAFTA2022,NAFTA,Vanadium,2022,0.214775,16.578472,0.502120,0.427737,31.602510
104,ZincNAFTA2022,NAFTA,Zinc,2022,0.010950,0.050845,0.138882,0.078843,1.901065
105,ZirconiumNAFTA2022,NAFTA,Zirconium,2022,0.071479,0.394452,0.194716,0.367096,2.259305